#services used to define the services that will be run in the Docker Compose environment
services:
  minio:
    image: minio/minio@sha256:14cea493d9a34af32f524e538b8346cf79f3321eff8e708c1e2960462bd8936e
    #first minio for server name and second image name for the server and the sha256 is the image digest to pin the image to a specific version
    command: server /data --console-address ":9001"
    #command to start the minio server and specify the data directory and console address
    ports:
        - "9000:9000"
    #Host port: Container port 
        - "9001:9001"
    #ports to expose the minio server and console to the host machine
    environment:
        MINIO_ROOT_USER: ${MINIO_USERNAME}
        # $ is used to reference the environment variable defined in the .env file and set the root user for the minio server
        MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    #environment variables to set the root user and password for the minio server
    volumes:
      - minio_data:/data
    #volume to persist the data stored in the minio server so even when container destroyed the data will be available in the volume
    #This tell to mount this volume to the /data directory in the container so that the data stored in the minio server will be persisted in the volume

  minio-init:
    image: enterprise-minio-init:1.0
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_USERNAME: ${MINIO_USERNAME}
      MINIO_PASSWORD: ${MINIO_PASSWORD}
    depends_on:
      - minio
    # Run the minio-init container after the minio container is up and running
    restart: "no"
    # Run the minio-init container only once and do not restart it after it has completed its task

  spark-master:
   image: enterprise-spark:4.2.0
   #image to use for the spark master container
   command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    #command to start the spark master container
    #[] - used two command inside a single command to start the spark master container
   ports:
     - "8080:8080"
    #ports to expose the spark master web UI to the host machine
    #we left 7077 port because it is the default port for spark master to communicate with spark workers and we don't need to expose it to the host machine

  spark-worker-1:
    image: enterprise-spark:4.2.0
    #image to use for the spark worker container
    environment:
      AWS_ACCESS_KEY_ID: ${MINIO_USERNAME}
      AWS_SECRET_ACCESS_KEY: ${MINIO_PASSWORD}
      #environment variables to set the AWS access key and secret access key for the spark worker container to connect to the minio server
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    #command to start the spark worker container, used woker class and specify the spark master URL to connect to the spark master container

  spark-worker-2:
    image: enterprise-spark:4.2.0
    #image to use for the spark worker container
    environment:
      AWS_ACCESS_KEY_ID: ${MINIO_USERNAME}
      AWS_SECRET_ACCESS_KEY: ${MINIO_PASSWORD}
      #environment variables to set the AWS access key and secret access key for the spark worker container to connect to the minio server
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    #command to start the spark worker container, used woker class and specify the spark master URL to connect to the spark master container

  spark-driver:
    #image to use for the spark driver container, for learning and development purposes, we can use the same image as the spark master and worker containers
    image: enterprise-spark:4.2.0
    environment:
      AWS_ACCESS_KEY_ID: ${MINIO_USERNAME}
      AWS_SECRET_ACCESS_KEY: ${MINIO_PASSWORD}
      PYTHONPATH: /workspace/backend:/opt/spark/python
      SPARK_CONF_DIR: /workspace/infrastructure/config/spark
      #Spark_conf_dir is used to specify the directory where the spark configuration files are located, in this case, we are using the spark configuration files from the infrastructure/config/spark directory in the workspace
    volumes:
      - ./:/workspace
    ports:
      - "4040:4040"
    command: [ "sleep", "infinity" ]
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
      - minio

  spark-history-server:
    image: enterprise-spark:4.2.0
    environment:
      AWS_ACCESS_KEY_ID: ${MINIO_USERNAME}
      AWS_SECRET_ACCESS_KEY: ${MINIO_PASSWORD}
      SPARK_HISTORY_OPTS: "-Dspark.history.fs.logDirectory=s3a://spark-events/"
    volumes:
      - ./infrastructure/config/spark:/opt/spark/conf
    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.history.HistoryServer
    ports:
      - "18080:18080"
    depends_on:
      - minio


volumes:
  minio_data:
    driver: local
#Tells create a local volume named minio_data to store the data for the minio server
#volume definition to create a local volume named minio_data to store the data for the minio server

