# S3A filesystem implementation
fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem

# MinIO endpoint inside the Docker Compose network
fs.s3a.endpoint=http://minio:9000

# MinIO is an S3-compatible third-party object store
fs.s3a.path.style.access=true

# MinIO in our local environment uses HTTP
fs.s3a.connection.ssl.enabled=false 