#Allocating 2GB of memory to the Spark driver
spark.driver.memory=2g

#Allocating 2GB of memory to each Spark executor
spark.executor.memory=2g

#Allocating cores to the Spark executors
spark.executor.cores=4

# Maximum total CPU cores requested by this application
spark.cores.max=8

# ==========================================
# Spark Event Logging
# ==========================================

# Enable event logging for completed applications
spark.eventLog.enabled=true

# Store Spark event logs in MinIO
spark.eventLog.dir=s3a://spark-events/