#Allocating 2GB of memory to the Spark driver
spark.driver.memory=2g

#Allocating 2GB of memory to each Spark executor
spark.executor.memory=2g

#Allocating cores to the Spark executors
spark.executor.cores=4

# Maximum total CPU cores requested by this application
spark.cores.max=8

# ==========================================
# Spark Event Logging
# ==========================================

# Enable event logging for completed applications
spark.eventLog.enabled=true

# Store Spark event logs in MinIO
spark.eventLog.dir=s3a://spark-events/

# ==========================================
# S3A / MinIO Object Storage
# ==========================================

# Use Hadoop's S3A filesystem implementation
spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem

# MinIO endpoint inside the Docker Compose network
spark.hadoop.fs.s3a.endpoint=http://minio:9000

# Required for MinIO's S3-compatible API
spark.hadoop.fs.s3a.path.style.access=true

# MinIO is using HTTP in the local environment
spark.hadoop.fs.s3a.connection.ssl.enabled=false